### PR TITLE
Fix Virtual Keyboard problem

### LINKED ISSUE #345: Virtual keyboard distorts UI
On Android, the viewport changes to landscape layout  when the virtual keyboard is opening

### PR DESCRIPTION
**Pull request by taulinger**
fixes #345

### CODE REVIEW

File: src/modules/header/components/Header.js [hunk 1]
```diff
@@ -168,7 +143,7 @@ export class Header extends BaElement {
 				<mask class="header__background">
 				</mask>
```
Comment (taulinger) [inline src/modules/header/components/Header.js:144]: @alsturm Tag looks strange to me...

Comment (alsturm) [reply src/modules/header/components/Header.js:145]: change to div works (don't know why this is so)

**Review by thiloSchlemmer — APPROVED** [review]
