### PR TITLE
Fixes for PublicWebComponent

### LINKED ISSUE #3458: Web Component - Bug List
- [x] `modifyLayer(id, {visible:false|true})`  does not fire a `baChange` event
- [x]  `modifyLayer(id, {opactiy:0.5})`  does not fire a `baChange` event
- [x]  Properties `layersVisiblity` and `layersOpacity` throw a NullReferenceException when accessed in baLoad,  expected to return an `[]:bool` filled with initial layers
- [x]  If no layers exist anymore the `ba.layers` property should return an empty array. -> Currently: `['']`, Expected: `[]`

### PR DESCRIPTION
**Pull request by taulinger**
fixes #3458
see also #3459

### CODE REVIEW

File: src/modules/wc/components/PublicWebComponent.js [hunk 1]
```diff
@@ -348,55 +367,72 @@ export class PublicWebComponent extends MvuElement {
...
+		);
 	}
 
 	/**
-	 * Returns the opacity of the layers of the map
+	 * Returns the opacity of the layers of the map or `[]` if the map is not yet initialized.
+	 *
 	 * @type {Array<number>}
 	 */
 	get layersOpacity() {
```
Comment (herrmutig) [inline src/modules/wc/components/PublicWebComponent.js]: If WC is initialized like this: `<bayern-atlas l=""></bayern-atlas>`  then 
`layersOpacity`  returns an array with one entry:`[NaN]` . Expected `[]`
