### PR TITLE
fix matcher for cases of invalid idOrUrl

### LINKED ISSUE #982: IconService throws exception on invalid idOrUrl
...but should return null or IconResult

### PR DESCRIPTION
**Pull request by thiloSchlemmer**
fixes #982

### CODE REVIEW

File: src/services/IconService.js [hunk 1]
```diff
@@ -71,26 +71,31 @@ export class IconService {
...
+	  * @returns {IconResult|null}
 	*/
 	getIconResult(idOrUrlOrBase64) {
 		if (idOrUrlOrBase64 === this._default.base64) {
 			return this._icons.find(iconResult => iconResult.matches(Svg_Marker_Name));
 		}
-		return this.isLocal(idOrUrlOrBase64) ? this._icons.find(iconResult => iconResult.base64 === idOrUrlOrBase64) : this._icons.find(iconResult => iconResult.matches(idOrUrlOrBase64));
+
+		const findLocal = (base64) => this._icons.find(iconResult => iconResult.base64 === base64) || null;
+		const findRemote = (idOrUrl) => this._icons.find(iconResult => iconResult.matches(idOrUrl)) || null;
```
Comment (taulinger) [inline src/services/IconService.js:84]: We should always use the "nullish coalescing operator" instead of the "logical or operator" in such cases now 🤓

**Review by taulinger — APPROVED** [review]
Thx!
