### PR TITLE
Fix ol draw handler delete point on click

### LINKED ISSUE #900: modify drawing with click on vertex not delete the point.

### PR DESCRIPTION
**Pull request by thiloSchlemmer**
fixes #900

### CODE REVIEW

File: src/modules/map/components/olMap/handler/draw/OlDrawHandler.js [hunk 1]
```diff
@@ -695,7 +694,16 @@ export class OlDrawHandler extends OlLayerHandler {
 	}
 
 	_setSelection(ids = []) {
-		if (this._select) {
+		// Todo: abstract check for array equality (flat array) could be extracted to utils
+		const arrayEquals = (a, b) => {
+			return Array.isArray(a) &&
+				Array.isArray(b) &&
+				a.length === b.length &&
+				a.every((val, index) => val === b[index]);
```
Comment (taulinger) [inline src/modules/map/components/olMap/handler/draw/OlDrawHandler.js:702]: You can use `equals` from storeUtils.js for now. Later we can move this function to utils.js

Comment (thiloSchlemmer) [reply src/modules/map/components/olMap/handler/draw/OlDrawHandler.js:702]: thx

**Review by taulinger — APPROVED** [review]
Thx
