### PR TITLE
fix trigger to clear input.value in ImportToolContent

### LINKED ISSUE #904: import file; enable import of same file
in Chrome: 
after successfully import a file, selecting the same file with file-chooser does not results in a change-event and therefore prevents a second import.

### PR DESCRIPTION
**Pull request by thiloSchlemmer**
update event-trigger to input-label
fixes #904

### CODE REVIEW

File: src/modules/toolbox/components/importToolContent/ImportToolContent.js [hunk 1]
```diff
@@ -74,13 +74,13 @@ export class ImportToolContent extends AbstractToolContent {
 				</div>
 				<div class="ba-tool-container__content divider" >                						     				
 					<div class="tool-container__buttons">      
-						<label for='fileupload' class="tool-container__button" role="button" tabindex="0" target="_blank" id="share-api" title="upload" > 	                              
+						<label for='fileupload' class="tool-container__button" role="button" tabindex="0" target="_blank" id="share-api" title="upload" @focus=${onClear}>
```
Comment (taulinger) [inline src/modules/toolbox/components/importToolContent/ImportToolContent.js:77]: Would suggest to rename the function `onClear` to  `clear[Input]`. "On" would indicate a callback...

**Review by taulinger — APPROVED** [review]
Thx
